name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      PROJECT_DESCRIPTION: ${{ secrets.PROJECT_DESCRIPTION }}
      PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o poetry
        run: pipx install uv

      - name: Instalar dependências
        run: uv sync --frozen

      - name: Executar testes
        run: uv run task test
